# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hatt 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "hatt".freeze
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Robert Schultheis".freeze]
  s.date = "2018-07-05"
  s.description = "convention based approach to interfacing with an HTTP JSON API.".freeze
  s.email = "robert.schultheis@gmail.com".freeze
  s.executables = ["hatt".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Readme.md",
    "bin/hatt",
    "hatt.gemspec",
    "lib/hatt.rb",
    "lib/hatt/api_clients.rb",
    "lib/hatt/base.rb",
    "lib/hatt/blankslateproxy.rb",
    "lib/hatt/configuration.rb",
    "lib/hatt/dsl.rb",
    "lib/hatt/http.rb",
    "lib/hatt/json_helpers.rb",
    "lib/hatt/log.rb",
    "lib/hatt/mixin.rb",
    "lib/hatt/singleton_mixin.rb"
  ]
  s.homepage = "http://github.com/rschultheis/hatt".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14.1".freeze
  s.summary = "Make calls to HTTP JSON APIs with ease and confidence".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<faraday>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<tcfg>.freeze, ["~> 0.2.2"])
      s.add_runtime_dependency(%q<typhoeus>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<pry>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<awesome_print>.freeze, [">= 0"])
      s.add_development_dependency(%q<debase>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<ruby-debug-ide>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc2md>.freeze, [">= 0"])
    else
      s.add_dependency(%q<activesupport>.freeze, [">= 0"])
      s.add_dependency(%q<faraday>.freeze, [">= 0"])
      s.add_dependency(%q<multi_json>.freeze, [">= 0"])
      s.add_dependency(%q<tcfg>.freeze, ["~> 0.2.2"])
      s.add_dependency(%q<typhoeus>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<awesome_print>.freeze, [">= 0"])
      s.add_dependency(%q<debase>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<ruby-debug-ide>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc2md>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, [">= 0"])
    s.add_dependency(%q<faraday>.freeze, [">= 0"])
    s.add_dependency(%q<multi_json>.freeze, [">= 0"])
    s.add_dependency(%q<tcfg>.freeze, ["~> 0.2.2"])
    s.add_dependency(%q<typhoeus>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<awesome_print>.freeze, [">= 0"])
    s.add_dependency(%q<debase>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<ruby-debug-ide>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc2md>.freeze, [">= 0"])
  end
end

